# Generated by Django 3.2.10 on 2021-12-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='push_status',
            field=models.IntegerField(choices=[(0, 'seen'), (1, 'unseen'), (2, 'sent')], default=1),
        ),
    ]
