# Generated by Django 3.2.10 on 2021-12-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, 'seen'), (1, 'unseen'), (2, 'sent')], default=1),
        ),
    ]
