# Generated by Django 3.2.10 on 2021-12-23 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='policy',
        ),
        migrations.AddField(
            model_name='review',
            name='employees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
